### ISSUE TITLE
Avoid uploading and invalidating files that are already there

### ISSUE THREAD

**Issue by bfred-it** [jelz/6xs#1]
AWeSome module here, this is the only one that I found that works. :smile:

Only issue is that it always uploads and invalidates all the files, rather than _sync_ it. It would be nice to have it either remember what's there before uploading/invalidating it. I saw some other modules saving a list md5's in a local cache. That could be a file like this stored on the bucket itself (this would allow usage in a CI server):

```
index.html:9ba0ebd1cc405bc5e20b9ce78760a116
style.css:142cdce62f139df95fe59c1443b33437
```

It's not a big deal given the costs of the upload/invalidation, but it could speed it up considerably for larger websites.

**Comment by jelz** [comment]
Thank you for your feedback. Saving hashes in S3 is a great idea.

The plan for 6xs was big and loud but development stopped as soon as it met my rather basic requirements (take a bunch of files, make sure that people will see new version in next 15 minutes).

Until this day I only knew about me and my friend using this tool. I'm a little bit time-constrained, but if we'll get one more person backing this feature request then I'll jump back to the code :)

Of course PRs are more than welcomed!

**Comment by bfred-it** [comment]
Cool! If you start sharing it around and suggesting it to who asks for it online I'm sure more people will be using it and those stars will be flowing it :P

**Comment by MateuszKubuszok** [comment]
I created PR with a workaround for this issue - CF invalidations filter. Theoretically one could implement filter, that uses e.g. Git or some comparison against previous S3 content to tell which files should be invalidated and which should not. Alternativelly one could just check manually and just write down while/blacklisted files manually.
