### ISSUE TITLE
libmagic doesn't detect SVG correctly

### ISSUE THREAD

**Issue by bfred-it** [jelz/6xs#2]
libmagic detects this `.svg` file as text/plain, probably simply because there's no full SVG header:

```svg
<svg width="433" height="191" viewBox="0 0 433 191" xmlns="http://www.w3.org/2000/svg"><path d="M118.4 130.8c0-1.1-.8-2.........................9 1-4.3.3-1.4 1-2.8 1.3-4.3.3-1.4-.2-3 .1-4.5.2-1.4.4-2.9.6-4.4.2-1.5.8-2.9.9-4.4-.2-.3-.5-2.3-1.6-4.1-.6-1.1-1.5-2.4-3.2-3-.6-.2-1.3-.9-2.1-1.1-1-.9-1.9 0-2.7 0z" fill="#FFF" fill-rule="evenodd"/></svg>
```
```
ASCII text, with very long lines, with no line terminators
```

I'm currently overriding its behavior with `contentTypeMap` but 6xs should probably detect svg files without change. Perhaps this would be a better match: https://github.com/broofa/node-mime

**Comment by jelz** [comment]
Tackled in https://github.com/jelz/6xs/commit/ab17d8bb625340c286d60cb60d21ee9238d08e95

**Comment by bfred-it** [comment]
Niiice! Thanks
