### ISSUE TITLE
gzipped mp4s fail to decode on Safari

### ISSUE THREAD

**Issue by bfred-it** [jelz/6xs#5]
~~Uploaded with 6xs: **~~
~~Uploaded via Transmit.app: **~~

The first one doesn't play in Safari, the second one works everywhere.

6xs should probably avoid gzipping compressed files in the first place. The industry standard goes for a format whitelist: https://github.com/h5bp/server-configs-apache/blob/master/dist/.htaccess#L741-L773

**Comment by bfred-it** [comment]
I ended up disabling gzip altogether, I forgot that CloudFront can do it automatically https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/

**Comment by jelz** [comment]
Fix released in v0.5.0, reused the list you've provided, thanks!
